### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by By-PorfecTo** [Aeonss/BubbleBlaster#24]
Error

![ScreenShot_20240118035533](https://github.com/Aeonss/BubbleBlaster/assets/92230690/b64a31c0-0ad6-4ec4-a81a-f810ae9bc071)

it gives an error when converting this jpg
![01](https://github.com/Aeonss/BubbleBlaster/assets/92230690/82f72de5-d250-42db-bb2c-f13d13795f0a)

**Comment by Aeonss** [comment]
Hmm, I'm not getting the same error.

**Comment by By-PorfecTo** [comment]
> Hmm, I'm not getting the same error.

I solved the problem at the top, it was caused by non-utf-8 characters in the file path, this problem was solved when the pc ran from the root directory, but this time it does not do the translation process, as far as I understand, it does not detect the writings on the image.


https://github.com/Aeonss/BubbleBlaster/assets/92230690/56735b68-1a85-445e-860f-2dfd64611e6c

**Comment by Aeonss** [comment]
Can you send the image you're using for the turkish bubble blaster

**Comment by By-PorfecTo** [comment]
> Can you send the image you're using for the turkish bubble blaster

Example site https://asuratoon.com/1398222385-academys-genius-swordmaster-chapter-1/ I downloaded it from this site and tried it

**Comment by Aeonss** [comment]
I still can't get the issue, make sure you're using the language that is on the webtoon. For example, in the link you posted, it is in english, so you want the language on BubbleBlaster to be English.

**Comment by Ayaan3216** [comment]
![Uploading test_ocr.png…]()

**Comment by Aeonss** [comment]
Try the latest version
